# Generated by Django 5.2.17 on 2026-09-30 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('total_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_quantity__lte', models.F('total_quantity'))), name='available_not_above_total')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=24, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course', models.CharField(max_length=120)),
                ('year_level', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('borrowed_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('returned_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned'), ('lost', 'Lost')], default='borrowed', max_length=12)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='tracker.equipment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='tracker.student')),
            ],
            options={
                'ordering': ['-borrowed_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='borrow_quantity_at_least_one')],
            },
        ),
    ]
